/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xyz_holocons_mc_headtexturefixer_Native */

#ifndef _Included_xyz_holocons_mc_headtexturefixer_Native
#define _Included_xyz_holocons_mc_headtexturefixer_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xyz_holocons_mc_headtexturefixer_Native
 * Method:    normalizeTexture
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_xyz_holocons_mc_headtexturefixer_Native_normalizeTexture
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
