name: Build

on: [ push ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Rust toolchain
      run: rustup target add wasm32-wasip1
    - name: Build with Cargo
      run: cargo build --workspace --release --verbose --target=wasm32-wasip1
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }}-${{ github.sha }}
        path: target/*.jar
